#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc	monitor	DP-0 -d I II III
bspc	monitor	DP-4 -d I II III

bspc config	border_width        7
bspc config	window_gap          7
bspc config	split_ratio          0.52
bspc config	borderless_monocle   true
bspc config	gapless_monocle      true
bspc config	border_width         0.5
bspc config	focus_follows_pointer true

bspc rule -a	Gimp desktop='^8' state=floating follow=on
bspc rule -a	Chromium desktop='^2'
bspc rule -a	mplayer2 state=floating
bspc rule -a	Kupfer.py focus=on
bspc rule -a	Screenkey manage=off

picom --experimental-backends --config $HOME/.config/picom/picom.conf & picom -b &
feh --bg-fill /usr/share/wallpapers/p1C5/netBlue.jpg &
xsetroot -cursor_name left_ptr & clipmenud &
systemd-inhibit --what=handle-power-key sleep infinity &
polybar -q bottom -c ~/.config/polybar/themes/simple.ini &
polybar -q bottom -c ~/.config/polybar/themes/47z1.ini &
