#!/bin/bash
# Author: Roi Diéguez - aka 47z!Lu7h

# --> Check if stdout is a terminal...
if test -t 1; then
    # --> See if it supports colors...
    ncolors=$(tput colors)

	if test -n "$ncolors" && test $ncolors -ge 8; then
		under='$(tput smul)'		# --> Set underline
		rem_under='$(tput rmul)'	# --> Remove underline
		bold="$(tput bold)"
		stnd="$(tput smso)"
		end="$(tput sgr0)"
		black="$(tput setaf 0)"
		red="$(tput setaf 1)"
		green="$(tput setaf 2)"
		yellow="$(tput setaf 3)"
		blue="$(tput setaf 4)"
		purple="$(tput setaf 5)"
		cyan="$(tput setaf 6)"
		white="$(tput setaf 7)"
	fi
fi

# --> Globals
declare -r packages="zsh rofi kitty git jq cmake npm g++ gettext feh dash bat meson neofetch wget curl xclip net-tools openvpn html2text fzf rlwrap gpick meson trash-cli brightnessctl qt5ct jsbeautifier lxappearance"
declare -r dpnDeb_Bspwm="libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-shape0-dev"
declare -r dpnDeb_Poly="build-essential cmake cmake-data pkg-config python3-sphinx python3-packaging libuv1-dev libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev"
declare -r dpnDeb_Picom="libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl-dev libegl-dev libpcre2-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev"
declare -r dpnFed_Bspwm="libxcb xcb-util xcb-util-wm xcb-util-keysyms libxcb-devel xcb-util-wm-devel xcb-util-keysyms-devel xcb-util-devel"
declare -r dpnFed_Picom="dbus-devel gcc libconfig-devel libdrm-devel libev-devel libX11-devel libX11-xcb libXext-devel libxcb-devel libGL-devel libEGL-devel meson pcre2-devel pixman-devel uthash-devel xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel"
declare -r dpnFed_Poly="gcc-c++ clang cmake @development-tools python3-sphinx python3-packaging cairo-devel libuv xcb-util-devel libxcb-devel xcb-proto xcb-util-image-devel xcb-util-wm-devel xcb-util-xrm-devel xcb-util-cursor-devel alsa-lib-devel pulseaudio-libs-devel i3-wm jsoncpp-devel libmpdclient-devel libcurl-devel wireless-tools-devel libnl3-devel"
declare -r dpnArch_Bspwm="libxcb xcb-util xcb-util-wm xcb-util-keysyms"
declare -r cwd=$(pwd)
declare -r OS=$(cat /etc/*release | grep '^ID_LIKE' | awk '{print $NF}' FS='=')
declare -r VERSION=$(cat /etc/*release | grep '^VERSION_ID' |  awk '{print $NF}' FS='=' | tr -d '"' )
declare -r NAME=$(cat /etc/*release | grep '^NAME' | awk '{print $NF}' FS='='| tr -d '"' |  awk '{print $1}')
declare -r ID=$(cat /etc/*release | grep '^ID' | awk '{print $NF}' FS='=')

trap ctrl_c INT

	# --> Banner
function banner(){
echo -ne "\t\t\t${red}${bold}
▄█████  ██████ ██▓███  █     █░███▄ ▄███▓▄████▄  ██▓    ██▓▄████▄
▓██████▒██    ▒▓██░  ██▓█░ █ ░█▓██▒▀█▀ ██▒██▀ ▀█ ▓██▒   ▓██▒██▀ ▀█
█    ▄█░ ▓██▄  ▓██░ ██▓▒█░ █ ░█▓██    ▓██▒▓█    ▄▒██░   ▒██▒▓██
▒██░█▀   ▒   ██▒██▄█▓▒ ░█░ █ ░█▒██    ▒██▒▓▓▄ ▄██▒██░   ░██▒▓▓▄ ▄██▒
░▓█  ▀█▒█████▒▒██▒ ░  ░░██▒██▓▒██▒   ░██▒ ▓███▀ ░██████░██▒ ▓███▀ ░
░▒▓███▀▒ ▒▓▒ ▒ ▒▓▒░ ░  ░ ▓░▒ ▒ ░ ▒░   ░  ░ ░▒ ▒  ░ ▒░▓  ░▓ ░ ░▒ ▒░
░▒░  ░░ ${bold}${red}By ${cyan}47z!Lu7h${end}${bold}${red}${standout} :)${red}  ░ ░ ░    ▒    ░ ░  ░      ░ ░    ░
░ ░		▒ ░	░	░	░${end}\n"
}

	# --> msg exit when ctrl+c
function ctrl_c(){
	echo -ne "\n\n\t\t${bold}${red}<|[${black}!${red}]|> ${cyan}Ctrl+C ${black}--->${red}Exiting${cyan}!! ${red}\n\n\n"
	exit 1
}

	# --> Complie Bspwm & Sxhkd
function compile_bspwm(){
	tput cnorm

	mkdir bspwm && cd bspwm
	echo -ne "\n\n\t${bold}${cyan}<|[+]|>${green}$ Cloning bspwm & sxhkd${cyan} -->${end}${cyan}\n\n"
	sleep 1 && git clone "https://github.com/baskerville/bspwm.git" && cd bspwm && make && sudo make install
	if [ $? -eq 0 ]; then
		echo -ne "\n\t\t${bold}${cyan}<|[+]|>${green} Cloning Sxhkd ${cyan}~~${bold}${cyan}>\n\n\n" && sleep 1 &&
		git clone "https://github.com/baskerville/sxhkd.git" && cd sxhkd && make && sudo make install
		if [ $? -eq 0 ]; then
			cd ../../../ && rm -rf bspwm
		fi
	fi

	tput civis
}

	# --> Compile polybar
function compile_polybar() {
	tput cnorm

	mkdir polybar && cd polybar
	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & compiling Polybar${cyan}~~${bold}${cyan}> ${end}${cyan}\n\n\n" && sleep 1
	git clone --recursive "https://github.com/polybar/polybar" && cd polybar && mkdir build && cd build && cmake ..
	if [ $? -eq 0 ]; then
		make -j$(nproc) && sudo make install
		if [ $? -eq 0 ]; then
			cd ../../../ && rm -rf polybar
		fi
	fi

	tput civis
}

	# --> Compile Picom
function compile_picom() {
	tput cnorm

	mkdir picom && cd picom
	echo -ne "\n\t${bold}${cyan}|[+]|> ${end}${bold}${white}${bold} Cloning & compliling Picom ${end}${cyan}~~${bold}${cyan}>${cyan}\n\n\n"
	sleep 1 && git clone "https://github.com/yshui/picom.git" && cd picom
	if [ $? -eq 0 ]; then
		git submodule update --init --recursive && meson setup --buildtype=release . build
		if [ $? -eq 0 ]; then
			ninja -C build && ninja -C build install
			if [ $? -eq 0 ]; then
				cd ../../ && rm -rf picom
				echo -ne "\t${end}${cyan}󱞩 ${bold}${green}   ${end}${white}${bold}󰨾 ${end}${white}  ${bold}${purple} ${cyan} "
			fi
		fi
	fi

	tput civis
}

	# --> VS-Code
function code() {
	tput cnorm

		if [ $OS = debian ]; then
			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing VS Code ${end}${cyan}~~${bold}${cyan}> \n\n"
			sleep 1
			sudo apt-get install wget gpg && wget -qO- "https://packages.microsoft.com/keys/microsoft.asc" && gpg --dearmor > packages.microsoft.gpg
			if [ $? -eq 0 ]; then
				sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
				sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
				if [ $? -eq 0 ]; then
					rm -f packages.microsoft.gpg &&
					sudo apt install apt-transport-https -y &&
					sudo apt update && sudo apt install code -y
					if [ $? -eq 0 ]; then
						code & disown && sleep 4 && sudo killall code && cp -r $cwd/misc/code/user/* ~/.config/Cod*/User/
					fi
				fi
			fi

		elif [ $OS = fedora ]; then
				echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing VS Code ${end}${cyan}~~${bold}${cyan}> \n\n"

				sleep 1 && sudo rpm --import "https://packages.microsoft.com/keys/microsoft.asc" &&
				sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
				if [ $? -eq 0 ]; then
					dnf check-update && sudo dnf install code
					code & disown; sleep 3 && sudo killall code && cp -r $cwd/misc/code/user/* ~/.config/Cod*/User/
			fi

		fi
	tput civis
}

	# --> Lsd
function lsd(){
	tput cnorm

	if [ $OS = debian ]; then
		sudo apt install lsd -y
		if [ $? -ne 0 ]; then
			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Downloading lsd ${end}${cyan}~~${bold}${cyan}> \n\n"
			sleep 1 && wget "https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb" -O lsd.deb && sudo dpkg -i lsd.deb && rm lsd.deb
		fi

	elif [ $OS = arch ]; then
		sudo pacman -S lsd

	elif [ $OS = fedora ]; then
		dnf install lsd
	fi

	tput civis
}

	# --> Firefox-esr
function firefox_esr() {
	tput cnorm

	which firefox-esr >/dev/null
	if [ $? -eq 0 ]; then
		if [ -d ~/.mozilla/ ]; then
			cp -r $cwd/misc/home/.mozilla/firefox/chrome		~/.mozilla/*firefox*/*default-esr*/
		else
			echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Setting firefox-esr theme${bold}${cyan}! \n\n"
			firefox-esr & disown; sleep 4 && sudo killall firefox-esr && sleep 2 &&
			cp -r $cwd/misc/home/.mozilla/firefox/chrome		~/.mozilla/*firefox*/*default-esr*/
		fi
	else
		if  [ $OS = debian ]; then
			sudo apt update && sudo apt install firefox-esr -y && sudo apt autoremove -y && sudo apt autoclean -y &&
			firefox-esr & disown; sleep 4 && sudo killall firefox-esr && sleep 1 &&
			cp -r $cwd/misc/home/.mozilla/firefox/chrome/		$HOME/.mozilla/*firefox-*/*default-esr*/

		elif [ if $NAME = Ubuntu]; then
			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing firefox-esr${cyan}! \n"
			sleep 1 && sudo add-apt-repository ppa:mozillateam/ppa && sudo apt update && sudo apt install firefox-esr &&
			firefox-esr & disown; sleep 4 && sudo killall firefox-esr && sleep 1 &&
			cp -r  $cwd/misc/home/.mozilla/firefox/chrome		$HOME/.mozilla/*firefox-*/*.default-esr*/
		fi
	fi

	tput civis
}

	# --> Complie Nvim & cloning NvChad
function nvim() {
	tput cnorm

	which nvim >/dev/null
	if [ $? -eq 0 ]; then
		echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${end}${blue}Cloning Nvim~NvChad${cyan} -->\n\n\n" && sleep 1 &&
		rm -rf ~/.config/nvim; rm -rf ~/.local/share/nvim; rm -rf ~/.cache/nvim; sudo rm -rf ~/.config/nvim; sudo rm -rf ~/.local/share/nvim; sudo rm -rf ~/.cache/nvim
 		sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim; sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim
		if [ $? -eq 0 ]; then
			git clone --depth 1 "https://github.com/NvChad/NvChad" ~/.config/nvim  && sudo git clone --depth 1 "https://github.com/NvChad/NvChad" /root/.config/nvim
		fi
	else
		mkdir nvim && cd nvim
		echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${end}${blue}Cloning & compiling neovim + cloning NvChad${cyan} -->\n\n\n" && sleep 1 &&
		git clone "https://github.com/neovim/neovim" && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install
		if [ $? -eq 0 ]; then
			rm -rf ~/.config/nvim; rm -rf ~/.local/share/nvim; rm -rf ~/.cache/nvim; sudo rm -rf ~/.config/nvim; sudo rm -rf ~/.local/share/nvim; sudo rm -rf ~/.cache/nvim
			sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim; sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim
			if [ $? -eq 0 ]; then
				git clone --depth 1 "https://github.com/NvChad/NvChad" ~/.config/nvim  && sudo git clone --depth 1 "https://github.com/NvChad/NvChad" /root/.config/nvim
				if [ $? -eq 0 ]; then
					cd ../../ && rm -rf nvim
				fi
			fi
		fi
	fi

	tput civis
}

	# --> Nice t@@L! ;D
function htb-Xplorer(){
	tput cnorm

	if [ -d /opt/h4Ck/htbXplorer-Plus ]; then
		echo -ne "\n\n${bold}${red}|${end}${red}󰓗 ${end}${white}<~${end}${white}${bold}${green} 󰆧 ${end}${white}~> \t${end}${red}H7b${yellow}~${red}Xpl@R3r ${yellow}already in the system${red}!\t${purple}${bold}󱝂 ${end}${white}${bold}${blue}󱜚 \n\n"; echo
	else
		echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Cloning htbXplorer from github${cyan}~~${bold}${cyan}> ${end}${cyan}\n\n"
		sleep 1 && sudo mkdir -p /opt/h4Ck/htbXplorer-Plus
	    if [ $? -eq 0 ]; then
			sudo git clone "https://github.com/4tz1Lu7h/htbXplorer-Plus.git" /opt/h4Ck/htbXplorer-Plus
		    if [ $? -eq 0 ]; then
				sudo chmod +x /opt/h4Ck/htbXplorer-Plus/htbXplorer &&
				echo -ne "\n\t\t${bold}${purple}~!~!~!~   ${cyan}HtbXplorer-${red}Plus ${cyan}done!   ${purple} ~!~!~!~\n\n"
			fi
		fi
	fi

	tput civis
}

		# -->  Fonts & Icons
function fonts(){

	if [ ! -f /usr/share/fonts/IosevkaNerdFont*.ttf ] >/dev/null 2>&1 ; then
		echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Getting Iosevka ${bold}font ${cyan}~~${bold}${cyan}> \n\n"
		wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/Iosevka.zip"
		sudo unzip -o Iosevka.zip -d /usr/share/fonts && rm Iosevka.zip
	fi

	if [ ! -f /usr/share/fonts/IosevkaTermNerdFont*.ttf ] >/dev/null 2>&1 ; then
		echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Getting IosevkaTerm ${bold}font ${cyan}~~${bold}${cyan}> \n\n"
		wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/IosevkaTerm.zip"
		sudo unzip -o IosevkaTerm.zip -d /usr/share/fonts && rm IosevkaTerm.zip
	fi

	if [ ! -f /usr/share/fonts/ComicShannsMono*.ttf ] >/dev/null 2>&1 ; then
		echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Getting IosevkaTerm ${bold}font ${cyan}~~${bold}${cyan}> \n\n"
		wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.0/ComicShannsMono.zip"
		sudo unzip -o ComicShannsMono.zip -d /usr/share/fonts && rm ComicShannsMono.zip
	fi

	sudo find /usr/share/fonts -name '*Windows Compatible*' -delete &&
	sudo find /usr/share/fonts -name '*FontMono*' -delete && fc-cache -fv

	if [ ! -d /usr/share/icons/candy*.ttf ] >/dev/null 2>&1 ; then
		echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Getting Candy ${bold}icons ${cyan}~~${bold}${cyan}> \n\n"
		wget "https://github.com/EliverLara/candy-icons/archive/refs/heads/master.zip" -O candy-icons.zip &&
		sudo unzip -o candy-icons.zip -d  /usr/share/icons && rm -rf candy-icons.zip
	fi

}

function zshPlugins(){

	# -->  Zsh plugins
	echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${end}${blue}Cloning zsh plugins ${cyan} -->\n\n${Bcyan}" && sleep 0.5

	if [ -d /usr/share/zsh/powerlevel10k ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}powerlevel10k ${yellow}\t ${bold}\t${green}done  ${end}\t"
	else
		sudo git clone --depth=1 "https://github.com/romkatv/powerlevel10k.git"	/usr/share/zsh/powerlevel10k
	fi

	if [ -d /usr/share/zsh-autocomplete ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}autocomplete ${yellow}\t\t ${bold}\t${green}done  ${end}\t"
	else
		sudo git clone --depth 1 -- "https://github.com/marlonrichert/zsh-autocomplete.git" /usr/share/zsh-autocomplete
	fi

	if [ -d /usr/share/zsh-fzf-history-search ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}fzf-history-search ${yellow}\t ${bold}\t${green}done  ${end}\t"
	else
		sudo git clone "https://github.com/joshskidmore/zsh-fzf-history-search.git"	/usr/share/zsh-fzf-history-search
	fi

	if [ -d /usr/share/zsh-syntax-highlighting ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}syntax-highlighting${yellow}\t ${bold}\t${green}done  ${end}\t"
	else
		export z5H5YNt4x=$(sudo git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git"	/usr/share/zsh-syntax-highlighting)
		if [ $OS = debian ]; then
			sudo apt install -y zsh-syntax-highlighting
			if [ $? -ne 0 ]; then
				${z5H5YNt4x}
			fi

		elif [ $OS = arch ]; then
			sudo pacman -S zsh-syntax-highlighting
			if [ $? -ne 0 ]; then
				${z5H5YNt4x}
			fi

		elif [ $OS = fedora ]; then
			sudo dnf install zsh-syntax-highlighting
			if [ $? -ne 0 ]; then
				${z5H5YNt4x}
			fi
		fi
	fi

	if [ -f ~/.zsh/git-completion.zsh ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}git-completion${yellow}\t ${bold}\t${green}done  ${end}\t"
	else
		wget "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh" -P ~/.zsh/
	fi

	if [ -f /usr/share/zsh/sudo.plugin.zsh ]; then
		echo -ne "\n\t${bold}${black} ${end}${blue}sudo.plugin ${yellow}\t\t ${bold}\t${green}done  ${end}\t"
	else
		sudo wget "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh" -P /usr/share/zsh/
	fi
}

function dotfiles(){

	echo -ne "\n\n\t${bold}${cyan}<[+]> ${end}${blue}Coping dotfiles ${cyan}\n\n" && sleep 1

	if [ -d $HOME/.config/bspwm ]; then
		mv $HOME/.config/bspwm $HOME/.config/bspwm.OLD
	fi

	if [ -d $HOME/.config/polybar ]; then
		mv $HOME/.config/polybar $HOME/.config/polybar.OLD
	fi

	if [ -d $HOME/.config/picom ]; then
		mv $HOME/.config/picom $HOME/.config/picom.OLD
	fi

	if [ -d $HOME/.config/sxhkd ]; then
		mv $HOME/.config/sxhkd $HOME/.config/sxhkd.OLD
	fi

	if [ -d $HOME/.config/kitty ]; then
		mv $HOME/.config/kitty $HOME/.config/kitty.OLD
	fi

	if [ -d $HOME/.config/rofi ]; then
		mv $HOME/.config/rofi $HOME/.config/rofi.OLD
	fi

	cp -r $cwd/config/* $HOME/.config/ &&
	mv $HOME/.zshrc $HOME/.zshrc.OLD && cp -r $cwd/misc/home/.*? $HOME &&
	sudo sed -i "s/bash/zsh/g" /etc/passwd && sudo ln -sf $HOME/.zsh /root &&
	sudo ln -s -f $HOME/.zshrc /root && sudo ln -s -f $HOME/.p10k.zsh /root
	if [ $? -eq 0 ]; then
		echo -ne "\n\t${bold}${black} ${end}${cyan}Dotfiles ${yellow}\t ${bold}\t${green}Done${Bgreen}! ${BIgreen} ${end}\n\n"
	fi
}

	# --> Multi d1stro
function main(){

	which code >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		code; fi

	which lsd >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		lsd; fi

	which firefox-esr >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		firefox_esr; fi

	which bspwm >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		if [ $OS = debian ]; then
			sudo apt install bspwm sxhkd -y
			if [ $? -ne 0 ]; then
				sudo apt install $dpnDeb_Bspwm -y && compile_bspwm
			fi

		elif [ $OS = arch ]; then
			sudo pacman -S bwpwm sxhkd
			if [ $? -ne 0 ]; then
				sudo pacman -S $dpnArch_Bspwm && compile_bspwm
			fi

		elif [ $OS = fedora ]; then
			sudo dnf install bspwm sxhkd
			if [ $? -ne 0 ]; then
				sudo dnf install $dpnFed_Bspwm && compile_bspwm
			fi
		fi
	fi

	which polybar >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		if [ $OS = debian ]; then
			sudo apt install polybar -y
			if [ $? -ne 0 ]; then
				sudo apt install $dpnDeb_Poly -y && compile_polybar
	           	fi

		elif [ $OS = arch ]; then
			sudo pacman -S polybar
			if [ $? -ne 0 ]; then
				compile_polybar
			fi

		elif [ $OS = fedora ]; then
			sudo dnf install polybar
			if [ $? -ne 0 ]; then
				sudo dnf install $dpnFed_Poly && compile_polybar
			fi
		fi
	fi

	which picom >/dev/null 2>&1
	if [ $? -ne 0 ]; then
		if [ $OS = debian ]; then
			sudo apt install picom -y
			if [ $? -ne 0 ]; then
				sudo apt install $dpnDeb_Poly -y && compile_picom
	           	fi

		elif [ $OS = arch ]; then
			sudo pacman -S picom
			if [ $? -ne 0 ]; then
				compile_picom
			fi

		elif [ $OS = fedora ]; then
			sudo dnf install picom
			if [ $? -ne 0 ]; then
				sudo dnf install $dpnFed_Poly && compile_picom
			fi
		fi
	fi

	htb-Xplorer && nvim && fonts && zshPlugins && dotfiles
}


################################################################################################################
           ###################  ~~~~~~~~~~~~~~~~ ¡| m41n |! ~~~~~~~~~~~~   #######################
###################################################################################################################

if [ "$EUID" == 0 ];then
	echo -e "\n\n${bold}${red}<|${bold}${black}[${bold}${red}!${bold}${black}]${bold}${red}|${bold}${black}[${bold}${red}!${bold}${black}]${bold}${red}|> \t${cyan}You do not have to be ${red}root ${cyan}to execute this script \t${stnd}${red};-)${end}\n\n" && sleep 1 
	exit 1
fi

banner

echo -ne "\n${cyan}<|${bold}[${red}+${cyan}]${end}${cyan}|${cyan}>${bold}${black} ~~~ ${end}${blue}This Script Will Add ${bold}${cyan}Bspwm ${end}${blue}Desktop Eviroment To Your Linux."
echo -ne "\n${cyan}<|${bold}[${red}+${cyan}]${end}${cyan}|${cyan}>${bold}${black} ~~~ ${end}${blue}Alongside with some other packages like:\n\t\t${cyan}Polybar${blue},${cyan} Picom${blue},${cyan} ZHS${blue},${cyan} Sxhkd${blue},${cyan} Nvim${blue},${cyan} VS-Code${blue},${cyan} firefox_esr${blue},${cyan} Lsd${blue}..."
echo -ne "\n\n\t${red}${bold}<${black}|${red}[${bold}${cyan}!${red}]${black}|${red}> ${end}${cyan}Are you sure you want to continue ${bold}? \n"
echo -ne "\n\t\t${end}${blue}[ ${bold}${cyan}y${end}${blue} / ${bold}${cyan}n${end}${blue} ]${red} ~~> ${bold}${cyan}"

read answer

if [ "$answer" != "${answer#[y/Y]}" ]; then

	echo -e "\n${blue}${bold}======================================================================== "
	echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${end}${red}${NAME} ${end}${blue}-|-|-|-|-"
	echo -e "${blue}${bold}======================================================================== "

	echo -ne "\n\t${cyan}${bold}<|[+]|> ${end}${blue}Upgrading System ${bold}${cyan}~~> \n\n"
	if [ $OS = debian ]; then
		if [ $NAME = Parrot ]; then
			sudo apt update && sudo parrot-upgrade -y && sudo apt autoremove -y && sudo dpkg --configure -a
		else
			sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo dpkg --configure -a
		fi

	elif [ $OS = arch ]; then
		echo -e "\n\n\t${blue}${bold}======= ${cyan}Still in development for ${bold}${yellow}Arch ${cyan}Distro ${end}${blue}======= \n\n" && sleep 1 && exit 1
	elif [ $OS = fedora ]; then
		echo -e "\n\n\t${blue}${bold}======= ${cyan}Still in development for ${bold}${yellow}Arch ${cyan}Distro ${end}${blue}======= \n\n" && sleep 1 && exit 1
	fi

	echo -ne "\n\t${bold}${cyan}<|[+]|> ${end}${blue}Installing Packages ${bold}${cyan}~~> \n\n"
	if [ $OS = debian ]; then
		sudo apt install -y $packages
	elif [ $OS = arch ]; then
		echo -e "\n\n\t${blue}${bold}======= ${cyan}Still in development for ${bold}${yellow}Arch ${cyan}Distro ${end}${blue}======= \n\n" && sleep 1 && exit 1
	elif [ $OS = fedora ]; then
		echo -e "\n\n\t${blue}${bold}======= ${cyan}Still in development for ${bold}${yellow}v ${cyan}Distro ${end}${blue}======= \n\n" && sleep 1 && exit 1
	fi

	main
	if [ $? -eq 0 ]; then
		echo -ne "\n${bold}${red}<${end}${black}|${end}${blue}[${bold}${red}!${end}${blue}]${black}|${bold}${red}>${end}${blue} To-Dos${red} ~~>${end} \
		\n\t${end}${red}~${end}${blue} Open a terminal & type ${end}${cyan}nvim ${end}${blue}to finish its configuration. \
		\n\t${end}${red}~$-name '{end}${blue} For dark theme Firefox-esr, open it & type => ${end}${cyan}about${red}:${end}${cyan}config${end}${blue}, then search for -->\
		\n\t${end}${red}<${end}${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${end}${red}>${blue}, and set it to ${bold}${cyan}True${end}${blue}."
		sleep 1 && echo -ne "\n\n\t${bold}${red}------/-/-/-/~~~~>> >>> ${end}${yellow}Try reboot and select ${bold}${red}Bspwm ${end}${yellow}as desktop Evironment. Enjoy!! ${stnd}${bold}${red};-)${end}${red} <<< <<~~~~~\-\-\-\------${end}\n\n\n" && sleep 1
	fi


elif [ "$answer" != "${answer#[n/N]}" ]; then
	sleep 0.3 && echo -ne "\n${cyan}<${bold}${black}|${cyan}[${black}!${cyan}]${bold}${black}|${end}${cyan}>${bold}${black} ~~~>>  ${red}Have a ${end}${cyan}Nice ${bold}${red}day${end}${black}!!  ${stnd}${red};=)${end}\n\n"
else
	sleep 0.3 && echo -ne "\n${cyan}<${bold}${black}|${cyan}[${black}!${cyan}]${bold}${black}|${end}${cyan}>\t${bold}${black} ~~~>> ${red}Bye${cyan}!! ${bold}${black}<<~~~~${end}\n\n"
fi
