#!/bin/bash
# Author: Roi Diéguez - aka 47z!Lu7h

# --> check if stdout is a terminal...
if test -t 1; then
    # --> see if it supports colors...
    ncolors=$(tput colors)

    if test -n "$ncolors" && test $ncolors -ge 8; then
        bold="$(tput bold)"
        underline="$(tput smul)"
        standout="$(tput smso)"
        end="$(tput sgr0)"
        black="$(tput setaf 0)"
        red="$(tput setaf 1)"
        green="$(tput setaf 2)"
        yellow="$(tput setaf 3)"
        blue="$(tput setaf 4)"
        purple="$(tput setaf 5)"
        cyan="$(tput setaf 6)"
        white="$(tput setaf 7)"
    fi
fi

# --> Globals
declare -r packages="linux-headers-$(uname -r) bspwm sxhkd polybar rofi picom kitty git cmake cmake-data extra-cmake-modules npm g++ gettext feh dash bat meson neofetch wget curl xclip net-tools openvpn html2text rlwrap gpick meson trash-cli xbacklight brightnessctl qt5ct python3-sphinx python3-packaging"

declare -r dependencies_Bspwm_deb="libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-randr0-dev libxcb-util0-dev libxcb-ewmh-dev libxcb-keysyms1-dev libxcb-shape0-dev"
declare -r dependencies_Poly_deb="build-essential cmake cmake-data pkg-config python3-sphinx python3-packaging libuv1-dev libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev"
declare -r dependencies_Picom_deb="libxext-dev libxcb1-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-present-dev libxcb-glx0-dev libpixman-1-dev libdbus-1-dev libconfig-dev libgl-dev libegl-dev libpcre2-dev libevdev-dev uthash-dev libev-dev libx11-xcb-dev"

declare -r dependencies_Bspwm_fed="libxcb xcb-util xcb-util-wm xcb-util-keysyms libxcb-devel xcb-util-wm-devel xcb-util-keysyms-devel xcb-util-devel"
declare -r dependencies_Picom_fed="dbus-devel gcc libconfig-devel libdrm-devel libev-devel libX11-devel libX11-xcb libXext-devel libxcb-devel libGL-devel libEGL-devel meson pcre2-devel pixman-devel uthash-devel xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel"
declare -r dependencies_Poly_fed="gcc-c++ clang cmake @development-tools python3-sphinx python3-packaging cairo-devel libuv xcb-util-devel libxcb-devel xcb-proto xcb-util-image-devel xcb-util-wm-devel xcb-util-xrm-devel xcb-util-cursor-devel alsa-lib-devel pulseaudio-libs-devel i3-wm jsoncpp-devel libmpdclient-devel libcurl-devel wireless-tools-devel libnl3-devel"

declare -r dependencies_Bspwm_arch="libxcb xcb-util xcb-util-wm xcb-util-keysyms"

trap ctrl_c INT

function banner(){
echo -ne "\n\n\t\t ${red}${bold}
 ▄█████  ██████ ██▓███  █     █░███▄ ▄███▓▄████▄  ██▓    ██▓▄████▄
▓██████▒██    ▒▓██░  ██▓█░ █ ░█▓██▒▀█▀ ██▒██▀ ▀█ ▓██▒   ▓██▒██▀ ▀█
█▒ ▄█░ ▓██▄  ▓██░ ██▓▒█░ █ ░█▓██    ▓██▒▓█    ▄▒██░   ▒██▒▓██
▒██░█▀   ▒   ██▒██▄█▓▒ ░█░ █ ░█▒██    ▒██▒▓▓▄ ▄██▒██░   ░██▒▓▓▄ ▄██▒
░▓█  ▀█▒█████▒▒██▒ ░  ░░██▒██▓▒██▒   ░██▒ ▓███▀ ░██████░██▒ ▓███▀ ░
░▒▓███▀▒ ▒▓▒ ▒ ▒▓▒░ ░  ░ ▓░▒ ▒ ░ ▒░   ░  ░ ░▒ ▒  ░ ▒░▓  ░▓ ░ ░▒ ▒░
▒░▒░  ░░ ░▒${bold}${cyan}By ${red}47z!Lu7h${end}${cyan}${tandout} :)${red}  ░ ░▒ ░     ▒ ░ ░ ░  ░      ░ ░  ▒  ░
░   ░ ░░░  ░ ░   ░     ░  ░░   ░  ░░ ▒  ░▒ ░  ░ ▒ ░░
 ░   ░   ░    ░░  ░ ░    ░ ░   ░ ░    ░   ░ ░   ░  ░    ░
 ░ ░		▒ ░	░	░	░${end}${end}"
}

function ctrl_c(){
	tput cnorm
	echo -ne "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Ctrl+C ${black}Exiting ${cyan}... ${end}\n\n\n"

	sudo rm -rf *.?  2>/dev/null
	exit 1
	tput civis
}

function main(){
	tput cnorm

	# -->  Nvim
	echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Nvim ${purple}NVCHAD ${blue}& copy files in config${cyan}: \n\n"
	sleep 2
	git clone "https://github.com/neovim/neovim" && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install
	if [ $? -eq 0 ]; then
		rm -rf ~/.config/nvim; rm -rf ~/.local/share/nvim; rm -rf ~/.cache/nvim; sudo rm -rf ~/.config/nvim; sudo rm -rf ~/.local/share/nvim; sudo rm -rf ~/.cache/nvim
		sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim; sudo rm -rf /root/.config/nvim; sudo rm -rf /root/.local/share/nvim; sudo rm -rf /root/.cache/nvim
		git clone "https://github.com/NvChad/NvChad" ~/.config/nvim --depth 1 && sudo git clone "https://github.com/NvChad/NvChad" /root/.config/nvim --depth 1
		if [ $? -eq 0 ]; then
			rm -rf ../neovim
			# --> Iosevka Font
			echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Getting Iosevka font ${end}${cyan} -->\n\n"
			sleep 2
			wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Iosevka.zip" && unzip Iosevka.zip -d ~/.local/share/fonts
			if [ $? -eq 0 ]; then
				rm -rf Iosevka.zip && fc-cache -v
				if [ $? -eq 0 ]; then
					echo -ne "\n\t\t${bold}${red}<|[*]|>${yellow}Fonts done!${red}<|[*]|>\n\n"
					sleep 2
					# -->  Lsd
					echo -ne "\n\t${bold}${cyan}<|[+]|>> ${blue}Getting lsd ${end}${cyan}--> \n"
					wget "https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb" -O lsd.deb
					if [ $? -eq 0 ]; then
						sudo dpkg -i lsd.deb && rm lsd.deb
						if [ $? -eq 0 ]; then
							echo -ne "\n\t\t${bold}${red} ~!~!~!~   ${yellow}Lsd installed!   ${red}~!~!~!~\n\n"
							sleep 2
							# -->  Zsh plugins
							echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning zsh Plugins${cyan} -->\n\n\n"
							sleep 2
							sudo rm -rf /usr/share/zsh*
							sudo git clone --depth=1 "https://github.com/romkatv/powerlevel10k.git" /usr/share/zsh/powerlevel10k
							sudo git clone "https://github.com/zsh-users/zsh-autosuggestions" /usr/share/zsh/plugins/zsh-autosuggestions
							sudo git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git" /usr/share/zsh/plugins/zsh-syntax-highlightiqng
							sudo git clone --depth=1 "https://github.com/marlonrichert/zsh-autocomplete.git" /usr/share/zsh/plugins/zsh-autocomplete
							sudo wget "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/sudo/sudo.plugin.zsh" -P /usr/share/zsh/plugins/
							if [ $? -eq 0 ]; then
								# -->  Copy files
								echo -ne "\n\t\t${bold}${red}~!~!~!~   ${yellow}Zsh plugins done!   ${red}~!~!~!~\n\n"
								sleep 2
								rm -rf ~/.config/bspwm ~/.config/sxhkd/ ~/.config/picom ~/.config/polybar ~/.config/rofi
								cp -r config/* ~/.config/
								cp misc/p10k.zsh ~/.p10k.zsh; cp misc/Xresources ~/.Xresources; sudo cp misc/root.p10k.zsh /root/.p10k.zsh
								cp misc/zshrc ~/.zshrc && sudo ln -s -f $HOME/.zshrc /root
								sudo cp -r misc/usrShare/* /usr/share/
								sudo sed -i "s/bash/zsh/g" /etc/passwd
								if [ $? -eq 0 ]; then
									echo -ne "\n\t\t${bold}${red}~!~!~!~   ${yellow}Config done!${red}   ~!~!~!~ ${standout}${black}:~D${end}\n\n"
									sleep 2
								else
								echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad copying the files ${red}${standout}:/  ${end}\n\n\n"
								sleep 2
								fi
							else
								echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad copying the files ${red}${standout}:/  ${end}\n\n\n"
								exit
							fi
						else
							echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad installing lsd ${red}${standout}:/  ${end}\n\n\n"
							exit
						fi
					else
						echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad downloading lsd ${red}${standout}:/  ${end}\n\n\n"
						exit
					fi
				else
					echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad installing the fonts ${red}${standout}:/  ${end}\n\n\n"
					exit 1
				fi
			else
				echo -ne "\n\n\t\t${bold}${red}<|[!]|>${black} Something went wrong downloading Iosevka Font ${red}${standout}:/  ${end}\n\n\n"
				exit 1
			fi
		else
			echo -e "\n\n\t\t${bold}${red}<|[!]|>${black} Something went wrong cloning NvChad repo ${red}${standout}:/  ${end}\n\n\n"
			exit 1
		fi
	else
		echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black}Something bad happen compiling Nvin${red}${standout} :/\n\n\n"
		exit 1
	fi

#			# --> Zsh-completions
#	if cat /etc/*release | grep "ID_LIKE" | grep -Ei "debian"; then export OS="Debian_10"; else export OS=""; fi
#	echo 'deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/$OS /' | sudo tee /etc/apt/sources.list.d/shells:zsh-users:zsh-completions.list
#	if [ $? -eq 0 ]; then
#		curl -fsSL https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_zsh-users_zsh-completions.gpg > /dev/null
#		if [ $? -eq 0 ]; then
#			sudo apt update && sudo apt install zsh-completions; sleep 2
#			echo -ne "\n\t\t${bold}${red} ~!~!~!~   ${yellow}zsh-completion installed!   ${red}~!~!~!~"
#		else
#			echo -e "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went bad installing zsh-completions${cyan}:/ ${end}\n\n\n"
#		fi
#	else
#		echo -e "\n\n\t\t${bold}${cyan}<|[!]|> ${red} Something went wrong Something went bad getting zsh-completions ${cyan}:/ ${end}\n\n\n"
#	fi

	tput civis
}

	# --> Complie Bspwm & Sxhkd
function compile_bspwm(){
	tput cnorm
	echo -ne "\n\n\t${bold}${cyan}<|[+]|>${green}$ Cloning bspwm${cyan}:${end}${cyan}\n\n"
	sleep 2

	git clone "https://github.com/baskerville/bspwm.git" && cd bspwm && make && sudo make install
	if [ $? -eq 0 ]; then
		sleep 2
		echo -ne "\n\t\t${bold}${cyan}<|[+]|>${green} Cloning Sxhkd${cyan}:\n\n\n"
		git clone "https://github.com/baskerville/sxhkd.git" && cd sxhkd && make && sudo make install
		if [ $? -eq 0 ]; then
			echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Bspwm & sxhkd done!   ${red}~!~!~!~\n\n"
			rm -rf ../../bspwm
		else
			echo -e "\n\t\t${bold}${red}<|[!]|> ${green} Failing compiling Sxhkd ${cyan}${standout}:/ ${end}\n"
			exit 1
		fi
	else
		echo -e "\n\t\t${bold}${red}<|[!]|> ${cyan}Failing Compliling bspwm ${red}${standout}:/  ${end}\n"
		exit 1
	fi
	tput civis
}

	# --> Compile Picom
function compile_picom(){
	echo -ne "\n\t${bold}${cyan}|[+]|> ${end}${bold}${white}${bold} Cloning & compliling Picom: ${end}${cyan}\n\n\n"
	sleep 2

	git clone "https://github.com/yshui/picom.git" && cd picom
	if [ $? -eq 0 ]; then
		git submodule update --init --recursive && meson setup --buildtype=release . build
		if [ $? -eq 0 ]; then
			ninja -C build && ninja -C build install
			if [ $? -eq 0 ]; then
				echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Picom done!   ${red}~!~!~!~\n\n"
				rm -rf ../picom
			else
				echo -e "\n\t\t${bold}${red}<|[!]|> ${green}Something went wrong Compiling Picom ${red}${standout}:/ ${end}\n"
				exit 1
			fi
		else
			echo -e "\n\t\t${bold}${red}<|[!]|> ${green}Anything bad happend compiling Picom ${red}${standout}:/ ${end}\n"
			exit 1
		fi
	else
		echo -e "\n\t\t${bold}${red}<|[!]|> ${green}We Cant Download From Github ${red}${standout}:/ ${end}\n"
		exit 1
	fi
	tput civis
}

	# --> Compile polybar
function compile_polybar(){
	tput cnorm
	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & compiling Polybar${cyan}: ${end}\n\n\n"
	sleep 2

	git clone --recursive "https://github.com/polybar/polybar" && cd polybar
	mkdir build && cd build && cmake ..
		if [ $? -eq 0 ]; then
		make -j$(nproc) && make -j$(nproc) && sudo make install
			if [ $? -eq 0 ]; then
				echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Polybar done!   ${red}~!~!~!~\n\n"
				rm -rf ../../polybar
			else
				echo -e "\n\n\t\t${bold}${red}|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/  ${end}\n"
				exit 1
			fi
		else
        	echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/ ${end}\n"
		fi
}

	# --> Rofi form source
function clone_rofi(){
	tput cnorm
	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & installing Rofi${cyan}:${end}\n\n\n"
	sleep 2

	git clone --depth=1 "https://github.com/adi1090x/rofi.git" && cd rofi
	if [ $? -eq 0 ]; then
		chmod +x setup.sh && ./setup.sh
		if [ $? -eq 0 ]; then
			echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Rofi done!   ${red}~!~!~!~"
                      	rm -rf ../rofi
                else
                	echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing setup Rofi ${red}${standout}:/ ${end}\n"
					exit 1
                fi
	else
        echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing cloning Rofi ${red}${standout}:/ ${end}\n"
		exit 1
	fi
	tput civis
}

	# --> Nice t@@L! ;D
function htb-Xplorer(){
	tput cnorm
	echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Cloning htbXplorer from github${cyan}: ${end}${cyan}\n\n"
	sleep 2

	sudo rm -r /opt/h4Ck/htbXplorer-Plus
        if [ $? -eq 0 ]; then
		sudo mkdir /opt/h4Ck/htbXplorer-Plus
	        if [ $? -eq 0 ]; then
			sudo git clone "https://github.com/4tz1Lu7h/htbXplorer-Plus.git" /opt/h4Ck/htbXplorer-Plus
		        if [ $? -eq 0 ]; then
				sudo chmod +x /opt/h4Ck/htbXplorer-Plus/htbXplorer
				echo -ne "\n\t\t${bold}${red}~!~!~!~   ${yellow}HtbXplorer-Plus done!   ${red} ~!~!~!~\n\n"
			else
		                echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Something went bad cloning the repo ${red}${standout}:/ ${end}\n"
				exit 1
			fi
		else
        		echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Something went bad creating the folder ${red}${standout}:/ ${end}\n"
			exit 1
		fi
	else
		echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Something went bad removing folders ${red}${standout}:/ ${end}\n"
		exit 1
	fi
	tput civis
}

#---------------------------------------------------------------------------------------------------------------------------------------------------------
# --> Main
#--------------------------------------------------------------------------------------------------------------------------------------------------------

if [ "$EUID" == 0 ];then
	echo -e "\n\n\t${bold}${red}<|[!]|[!]|> ${cyan}You do not to be ${red}root ${cyan}to execute this script ${standout}${red}; )${end}\n\n"
	exit
fi

banner

echo -ne "\n${bold}${cyan}|[*]|> ${end}${blue}This Script Will Add ${bold}${cyan}Bspwm ${end}${blue}Desktop Eviroment To Your Linux."
echo -ne "\n\t${blue}- It Will ${cyan}Overwrite ${blue}Some Files Stored In Your ${yellow}~/.config/${blue}.\n"
echo -ne "\t${blue}- Which includes: ${cyan}Bspwm${blue},${cyan} Sxhkd${blue},${cyan} Polybar${blue}, ${cyan}Rofi${blue}, ${cyan}Picom ${blue}& ${cyan}Kitty${blue}.\n\n"
echo -ne "${bold}${cyan}|[*]|> ${end}${blue}If you have any personal configuration in any of this folders, \n"
echo -ne "\t${blue}it is better to use a virtual machine or create a new user instead${bold}${blue} :)${end}\n\n\n"
echo -ne "\t${red}${bold}<|[!]|> ${cyan}Are you sure you want to ${red}continue? ${cyan}--> ${yellow}(y/n)${end}\n\n"

read answer

if [ "$answer" != "${answer#[Yy]}" ]; then
	if cat /etc/*release | grep "^NAME" | grep -Ei "Kali" > /dev/null; then

		echo -e "${blue}${bold}==================================================================== "
		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Kali ${cyan}distribution ${blue}-|-|-|-|-"
		echo -e "${blue}${bold}===================================================================="
		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System${cyan}: \n\n"
		sleep 2
		sudo apt update && sudo apt upgrade -y
		if [ $? -eq 0 ]; then
			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages & dependecies${cyan}: \n\n\n"
			sleep 2
			sudo apt install -y $dependencies_Bspwm_deb $dependencies_Picom_deb $dependencies_Poly_deb $packages
		    if [ $? -eq 0 ]; then
				htb-Xplorer
			    if [ $? -eq 0 ]; then
					main
					if [ $? -eq 0 ]; then
						sudo apt purge zsh\* -y && sudo apt install zsh -y
						sleep 2
						echo -ne "\n\n\t\t${yellow}<|[*]|> ${bold}${cyan}Done!!${yellow} :)\n"
						sleep 2
						echo -ne "\n\t\t${bold}${white}<|[*]|>${yellow} try reboot and select Bspwm as desktop evironment ${standout}${red}$;){end}\n"¡
						echo -ne "\n\t\t${bold}${white}<|[*]|>${yellow} Open a temrinal & type nvim to finsih the configuration ${standout}${red}$:D{end}\n\n\n"¡
					else
						echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with the installation ${red}${standout}:/ \n\n\n"
						sleep 2
						exit 1
					fi
				else
					echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with cloning de repo ${red}${standout}:/  ${end}\n\n\n"
					sleep 2
					exit 1
			fi
			else
				echo -ne "\n\n\t${bold}${red}<|[!]|>${yellow} Something went wrong installing the packages ${standout}${red}:/ ${end}\n\n\n"
				sleep 2
				exit 1
			fi
		else
			echo -ne "\n\n\t${bold}${red}<|[!]|> ${end}${bold}${yellow} Something went bad upgrading the System ${red}${standout}:/ ${end}\n\n\n"
			sleep 2
			exit 1
		fi



	else
		sleep 2
		echo -ne "\n\t${bold}${red}<|[!]|> ${green}Sorry, this OS ${green}is ${red}not ${green}supported ${standout}${red}:/ ${end}\n\n\n"
	fi
fi

