#!/bin/bash

IP=$(ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | head -n 1 | awk '/inet/ {print $2}' | cut -d'/' -f1)
INET=$(/usr/sbin/ifconfig |  grep -Ei "wlan|eth0|ens33|ens36|emp0s3" -A3 | grep inet)

if [[ -z "$INET" ]]; then
	echo "%{T8}%{F#bbe0ff} 󰯡 %{T6}%{F#888A}󰦎 %{T4}%{F#888AAF}Disconected!"
else
	echo "%{T0}%{F#bbe0ff} 󰀂 %{T6}%{F#888A} %{T2}%{F#888AAF}$IP"
fi
